export default {
  ADD_TEAM_SUCCESS : 'ADD_TEAM_SUCCESS',
  ADD_TEAM_REQUEST : 'ADD_TEAM_REQUEST',
  ADD_TEAM_FAILED : 'ADD_TEAM_FAILED',
  GET_TEAM_REQUEST: 'GET_TEAM_REQUEST',
  GET_TEAM_SUCCESS: 'GET_TEAM_SUCCESS',
  GET_TEAM_FAILED: 'GET_TEAM_FAILED',
  ADD_PLAYER_REQUEST: 'ADD_PLAYER_REQUEST',
  ADD_PLAYER_SUCCESS: 'ADD_PLAYER_SUCCESS',
  ADD_PLAYER_FAILED: 'ADD_PLAYER_FAILED',
}